server:
  port: 8002


spring:
  application:
    name: cloud-payment-service
  datasource:
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.128:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: mysql

eureka:
  client:
    #表示是否将自己注册进行EurkaServer默认为ture
    register-with-eureka: true
    #是否从EurekaServer抓取自己有的注册信息,默认为true，单节点无所谓，集群必须设置true才能配合ribbon使用负债均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #更改主机名称 因为有可能部署在不同的机器上，所以需要主机名称的设置
    instance-id: payment8002
    prefer-ip-address: true


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities # 如果这样写在xml入参直接写类名就好了


