server:
  port: 80



eureka:
  client:
    #表示是否将自己注册进行EurkaServer默认为ture
    register-with-eureka: true
    #是否从EurekaServer抓取自己有的注册信息,默认为true，单节点无所谓，集群必须设置true才能配合ribbon使用负债均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
feign:
  hystrix:
    enabled: true
